ImagesToLoad = {
    { spriteKey = "Documents:LMLadder", url = "http://i.imgur.com/xIqzbtJ.png" }, 
    { spriteKey = "Documents:LMHole", url = "http://i.imgur.com/o3a08eD.png" },
    { spriteKey = "Documents:LMPlayerB1", url = "http://i.imgur.com/lZBuLGQ.png" }, 
    { spriteKey = "Documents:LMPlayerB2", url = "http://i.imgur.com/eSj4r9g.png" }, 
    { spriteKey = "Documents:LMPlayerG1", url = "http://i.imgur.com/api8OpI.png" }, 
    { spriteKey = "Documents:LMPlayerG2", url = "http://i.imgur.com/86vF38r.png" },
    { spriteKey = "Documents:LMPlayerL1", url = "http://i.imgur.com/ZqLSUj2.png" }, 
    { spriteKey = "Documents:LMPlayerL2", url = "http://i.imgur.com/gfKRLMi.png" },
    { spriteKey = "Documents:LMPlayerP1", url = "http://i.imgur.com/x2vI7Gk.png" }, 
    { spriteKey = "Documents:LMPlayerP2", url = "http://i.imgur.com/U7860TA.png" },
    { spriteKey = "Documents:LMPlayerY1", url = "http://i.imgur.com/LQndLGf.png" }, 
    { spriteKey = "Documents:LMPlayerY2", url = "http://i.imgur.com/kfE2Yal.png" },
    { spriteKey = "Documents:LMRipsign", url = "http://i.imgur.com/OVaoNjo.png" }, 
    { spriteKey = "Documents:LMBargray", url = "http://i.imgur.com/gSB7EAr.png" }, 
    { spriteKey = "Documents:LMBarred", url = "http://i.imgur.com/5TDecbn.png" }, 
    { spriteKey = "Documents:LMGlasspanel", url = "http://i.imgur.com/rkz6v3L.png" }, 
    { spriteKey = "Documents:LMStone", url = "http://i.imgur.com/5dnSgbO.png" }, 
    { spriteKey = "Documents:LMGrass", url = "http://i.imgur.com/sjnBImb.png" },
}
